BaseUrl= "https://mRs-.github.io/"
LanguageCode= "en-us"
Title= "Marius Landwehr"
paginate = 5
DisqusShortname = "mRs-"
Copyright = "All rights reserved - 2017"
canonifyurls = true

[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/"
	weight = -120

[params]
  description = "Senior iOS Developer @CHECK24"
  cover = "images/cover.jpg"
  author = "Marius Landwehr"
  authorlocation = "Osnabrück, Germany"
  authorwebsite = "https://mrs-.github.io/"
  #bio= "my bio"
  logo = "images/logo.jpg"
  googleAnalyticsUserID = "UA-90154002-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "mRs-"
  twitterName = "mariusLAN"
  # facebookName = ""
  linkedinName = "marius-landwehr-bb99a976"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
